export const listOfCountry = [
  { label: "Afghanistan", value: "AFG" },
  { label: "Afrique du Sud", value: "ZAF" },
  { label: "Albanie", value: "ALB" },
  { label: "Algérie", value: "DZA" },
  { label: "Allemagne", value: "DEU" },
  { label: "Andorre", value: "AND" },
  { label: "Angola", value: "AGO" },
  { label: "Antigua-et-Barbuda", value: "ATG" },
  { label: "Arabie saoudite", value: "SAU" },
  { label: "Argentine", value: "ARG" },
  { label: "Arménie", value: "ARM" },
  { label: "Australie", value: "AUS" },
  { label: "Autriche", value: "AUT" },
  { label: "Azerbaïdjan", value: "AZE" },
  { label: "Bahamas", value: "BHS" },
  { label: "Bahreïn", value: "BHR" },
  { label: "Bangladesh", value: "BGD" },
  { label: "Barbade", value: "BRB" },
  { label: "Belgique", value: "BEL" },
  { label: "Bélize", value: "BLZ" },
  { label: "Bénin", value: "BEN" },
  { label: "Bhoutan", value: "BTN" },
  { label: "Biélorussie", value: "BLR" },
  { label: "Birmanie", value: "MMR" },
  { label: "Bolivie", value: "BOL" },
  { label: "Bosnie-Herzégovine", value: "BIH" },
  { label: "Botswana", value: "BWA" },
  { label: "Brésil", value: "BRA" },
  { label: "Brunei", value: "BRN" },
  { label: "Bulgarie", value: "BGR" },
  { label: "Burkina", value: "BFA" },
  { label: "Burundi", value: "BDI" },
  { label: "Cambodge", value: "KHM" },
  { label: "Cameroun", value: "CMR" },
  { label: "Canada", value: "CAN" },
  { label: "Cap-Vert", value: "CPV" },
  { label: "Centrafrique", value: "CAF" },
  { label: "Chili", value: "CHL" },
  { label: "Chine", value: "CHN" },
  { label: "Chypre", value: "CYP" },
  { label: "Colombie", value: "COL" },
  { label: "Comores", value: "COM" },
  { label: "Congo", value: "COG" },
  { label: "République démocratique du Congo", value: "COD" },
  { label: "Îles Cook", value: "COK" },
  { label: "Corée du Nord", value: "PRK" },
  { label: "Corée du Sud", value: "KOR" },
  { label: "Costa Rica", value: "CRI" },
  { label: "Côte d'Ivoire", value: "CIV" },
  { label: "Croatie", value: "HRV" },
  { label: "Cuba", value: "CUB" },
  { label: "Danemark", value: "DNK" },
  { label: "Djibouti", value: "DJI" },
  { label: "République dominicaine", value: "DOM" },
  { label: "Dominique", value: "DMA" },
  { label: "Égypte", value: "EGY" },
  { label: "Émirats arabes unis", value: "ARE" },
  { label: "Équateur", value: "ECU" },
  { label: "Érythrée", value: "ERI" },
  { label: "Espagne", value: "ESP" },
  { label: "Estonie", value: "EST" },
  { label: "Eswatini", value: "SWZ" },
  { label: "États-Unis", value: "USA" },
  { label: "Éthiopie", value: "ETH" },
  { label: "Fidji", value: "FJI" },
  { label: "Finlande", value: "FIN" },
  { label: "France", value: "FRA" },
  { label: "Gabon", value: "GAB" },
  { label: "Gambie", value: "GMB" },
  { label: "Géorgie", value: "GEO" },
  { label: "Ghana", value: "GHA" },
  { label: "Grèce", value: "GRC" },
  { label: "Grenade", value: "GRD" },
  { label: "Guatémala", value: "GTM" },
  { label: "Guinée", value: "GIN" },
  { label: "Guinée équatoriale", value: "GNQ" },
  { label: "Guinée-Bissao", value: "GNB" },
  { label: "Guyana", value: "GUY" },
  { label: "Haïti", value: "HTI" },
  { label: "Honduras", value: "HND" },
  { label: "Hongrie", value: "HUN" },
  { label: "Inde", value: "IND" },
  { label: "Indonésie", value: "IDN" },
  { label: "Irak", value: "IRQ" },
  { label: "Iran", value: "IRN" },
  { label: "Irlande", value: "IRL" },
  { label: "Islande", value: "ISL" },
  { label: "Israël", value: "ISR" },
  { label: "Italie", value: "ITA" },
  { label: "Jamaïque", value: "JAM" },
  { label: "Japon", value: "JPN" },
  { label: "Jordanie", value: "JOR" },
  { label: "Kazakhstan", value: "KAZ" },
  { label: "Kénya", value: "KEN" },
  { label: "Kirghizstan", value: "KGZ" },
  { label: "Kiribati", value: "KIR" },
  { label: "Kosovo", value: "KOS" },
  { label: "Koweït", value: "KWT" },
  { label: "Laos", value: "LAO" },
  { label: "Lésotho", value: "LSO" },
  { label: "Lettonie", value: "LVA" },
  { label: "Liban", value: "LBN" },
  { label: "Libéria", value: "LBR" },
  { label: "Libye", value: "LBY" },
  { label: "Liechtenstein", value: "LIE" },
  { label: "Lituanie", value: "LTU" },
  { label: "Luxembourg", value: "LUX" },
  { label: "Macédoine du Nord", value: "MKD" },
  { label: "Madagascar", value: "MDG" },
  { label: "Malaisie", value: "MYS" },
  { label: "Malawi", value: "MWI" },
  { label: "Maldives", value: "MDV" },
  { label: "Mali", value: "MLI" },
  { label: "Malte", value: "MLT" },
  { label: "Maroc", value: "MAR" },
  { label: "Îles Marshall", value: "MHL" },
  { label: "Maurice", value: "MUS" },
  { label: "Mauritanie", value: "MRT" },
  { label: "Mexique", value: "MEX" },
  { label: "Micronésie", value: "FSM" },
  { label: "Moldavie", value: "MDA" },
  { label: "Monaco", value: "MCO" },
  { label: "Mongolie", value: "MNG" },
  { label: "Monténégro", value: "MNE" },
  { label: "Mozambique", value: "MOZ" },
  { label: "Namibie", value: "NAM" },
  { label: "Nauru", value: "NRU" },
  { label: "Népal", value: "NPL" },
  { label: "Nicaragua", value: "NIC" },
  { label: "Niger", value: "NER" },
  { label: "Nigéria", value: "NGA" },
  { label: "Niue", value: "NIU" },
  { label: "Norvège", value: "NOR" },
  { label: "Nouvelle-Zélande", value: "NZL" },
  { label: "Oman", value: "OMN" },
  { label: "Ouganda", value: "UGA" },
  { label: "Ouzbékistan", value: "UZB" },
  { label: "Pakistan", value: "PAK" },
  { label: "Palaos", value: "PLW" },
  { label: "Panama", value: "PAN" },
  { label: "Papouasie-Nouvelle-Guinée", value: "PNG" },
  { label: "Paraguay", value: "PRY" },
  { label: "Pays-Bas", value: "NLD" },
  { label: "Pérou", value: "PER" },
  { label: "Philippines", value: "PHL" },
  { label: "Pologne", value: "POL" },
  { label: "Portugal", value: "PRT" },
  { label: "Qatar", value: "QAT" },
  { label: "Roumanie", value: "ROU" },
  { label: "Royaume-Uni", value: "GBR" },
  { label: "Russie", value: "RUS" },
  { label: "Rwanda", value: "RWA" },
  { label: "Saint-Christophe-et-Niévès", value: "KNA" },
  { label: "Sainte-Lucie", value: "LCA" },
  { label: "Saint-Marin", value: "SMR" },
  { label: "Saint-Vincent-et-les-Grenadines", value: "VCT" },
  { label: "Salomon", value: "SLB" },
  { label: "Salvador", value: "SLV" },
  { label: "Samoa", value: "WSM" },
  { label: "Sao Tomé-et-Principe", value: "STP" },
  { label: "Sénégal", value: "SEN" },
  { label: "Serbie", value: "SRB" },
  { label: "Seychelles", value: "SYC" },
  { label: "Sierra Leone", value: "SLE" },
  { label: "Singapour", value: "SGP" },
  { label: "Slovaquie", value: "SVK" },
  { label: "Slovénie", value: "SVN" },
  { label: "Somalie", value: "SOM" },
  { label: "Soudan", value: "SDN" },
  { label: "Soudan du Sud", value: "SDS" },
  { label: "Sri Lanka", value: "LKA" },
  { label: "Suède", value: "SWE" },
  { label: "Suisse", value: "CHE" },
  { label: "Suriname", value: "SUR" },
  { label: "Syrie", value: "SYR" },
  { label: "Tadjikistan", value: "TJK" },
  { label: "Tanzanie", value: "TZA" },
  { label: "Tchad", value: "TCD" },
  { label: "Tchéquie", value: "CZE" },
  { label: "Thaïlande", value: "THA" },
  { label: "Timor oriental", value: "TLS" },
  { label: "Togo", value: "TGO" },
  { label: "Tonga", value: "TON" },
  { label: "Trinité-et-Tobago", value: "TTO" },
  { label: "Tunisie", value: "TUN" },
  { label: "Turkménistan", value: "TKM" },
  { label: "Turquie", value: "TUR" },
  { label: "Tuvalu", value: "TUV" },
  { label: "Ukraine", value: "UKR" },
  { label: "Uruguay", value: "URY" },
  { label: "Vanuatu", value: "VUT" },
  { label: "Vatican", value: "VAT" },
  { label: "Vénézuéla", value: "VEN" },
  { label: "Vietnam", value: "VNM" },
  { label: "Yémen", value: "YEM" },
  { label: "Zambie", value: "ZMB" },
  { label: "Zimbabwé", value: "ZWE" },
];
