export const listOfCountry = [
    { value: "AF", label : "Afghanistan" },
    {value : "AX", label :"Aland Islands"},
    {value : "AL", label :"Albania" },
    {value : "DZ", label :"Algeria" },
    {value : "AS", label :"American Samoa" }, 
    {value : "CM", label :"Cameroon" },
    {value : "CA", label :"Canada" },                      
    {value : "CV", label :"Cape Verde" },
    {value : "CY", label :"Cyprus" }, 
    {value : "CZ", label :"Czech Republic" },
    {value : "DK", label :"Denmark" },
    {value : "DJ", label :"Djibouti" },
    {value : "DM", label :"Dominica" },
    {value : "DO", label :"Dominican Republic" },
    {value : "EC", label :"Ecuador" },                  
    {value : "EG", label :"Egypt" },
    {value : "SV", label :"El Salvador" },
    {value : "GQ", label :"Equatorial Guinea" },
    {value : "ER", label :"Eritrea" },
    {value : "EE", label :"Estonia" },
    {value : "ET", label :"Ethiopia" },
    {value : "FK", label :"Falkland Islands (Malvinas)" },
    {value : "FO", label :"Faroe Islands" },
    {value : "FJ", label :"Fiji" },
    {value : "FI", label :"Finland" },
    {value : "FR", label :"France" },
    {value : "GF", label :"French Guiana" },
    {value : "PF", label :"French Polynesia" },
    {value : "TF", label :"French Southern Territories"},
    {value : "GA", label :"Gabon" },
    {value : "GM", label :"Gambia" },
    {value : "GE", label :"Georgia" },
    {value : "DE", label :"Germany" },
    {value : "GH", label :"Ghana" },
    {value : "GI", label :"Gibraltar" },
    {value : "GR", label :"Greece" },
    {value : "GL", label :"Greenland" },
    {value : "GD", label :"Grenada" },
    {value : "GP", label :"Guadeloupe" },
    {value : "GU", label :"Guam" },
    {value : "GT", label :"Guatemala" },
    {value : "GG", label :"Guernsey" },
    {value : "GN", label :"Guinea" },
    {value : "GW", label :"Guinea-Bissau" },
    {value : "GY", label :"Guyana" },
    {value : "HT", label :"Haiti" },
    {value : "VA", label :"Vatican" },
    {value : "HN", label :"Honduras" },
    {value : "HK", label :"Hong Kong, Special Administrative Region of China" },
    {value : "HU", label :"Hungary" },
    {value : "IS", label :"Iceland" },
    {value : "IN", label :"India" },
    {value : "ID", label :"Indonesia" },
    {value : "IR", label :"Iran, Islamic Republic of" },
    {value : "IQ", label :"Iraq" },
    {value : "IE", label :"Ireland" },
    {value : "IM", label :"Isle of Man" },
    {value : "IL", label :"Israel" },
    {value : "IT", label :"Italy" },
    {value : "JM", label :"Jamaica" },
    {value : "JP", label :"Japan" },
    {value : "JE", label :"Jersey" },
    {value : "JO", label :"Jordan" },
    {value : "KZ", label :"Kazakhstan" },
    {value : "KE", label :"Kenya" },
    {value : "KI", label :"Kiribati" },
    {value : "KP", label :"Korea, Democratic People's Republic of" },
    {value : "KR", label :"Korea, Republic of" },
    {value : "KW", label :"Kuwait" },
    {value : "KG", label :"Kyrgyzstan" },
    {value : "LA", label :"Lao PDR" },
    {value : "LV", label :"Latvia" },
    {value : "LB", label :"Lebanon" },
    {value : "LS", label :"Lesotho" },
    {value : "LR", label :"Liberia" },
    {value : "LY", label :"Libya" },
    {value : "LI", label :"Liechtenstein" },
    {value : "LT", label :"Lithuania" },
    {value : "LU", label :"Luxembourg" },
    {value : "MO", label :"Macao, Special Administrative Region of China" },
    {value : "MK", label :"Macedonia, Republic of" },
    {value : "MG", label :"Madagascar" },
    {value : "MW", label :"Malawi" },
    {value : "MY", label :"Malaysia" },
    {value : "NG", label :"Nigeria" },
    {value : "NU", label :"Niue" },
    {value : "WS", label :"Samoa" },
    {value : "SM", label :"San Marino" },
    {value : "ST", label :"Sao Tome and Principe" },
    {value : "SA", label :"Saudi Arabia" },
    {value : "SN", label :"Senegal" },
    {value : "RS", label :"Serbia" },
    {value : "SC", label :"Seychelles" },
    {value : "SL", label :"Sierra Leone" },
    {value : "SG", label :"Singapore" },
    {value : "SX", label :"Sint Maarten" },
    {value : "SK", label :"Slovakia" },
    {value : "SI", label :"Slovenia" },
    {value : "SB", label :"Solomon Islands" },
    {value : "SO", label :"Somalia" },
    {value : "ZA", label :"South Africa" },
    {value : "GS", label :"South Georgia and the South Sandwich Islands" },
    {value : "SS", label :"South Sudan" },
    {value : "ES", label :"Spain" },
    {value : "LK", label :"Sri Lanka" },
    {value : "SD", label :"Sudan" },
    {value : "SR", label :"Suriname" },
    {value : "SJ", label :"Svalbard and Jan Mayen Islands" },
    {value : "SZ", label :"Swaziland" },
    {value : "SE", label :"Sweden" },
    {value : "CH", label :"Switzerland" },
    {value : "SY", label :"Syrian Arab Republic (Syria)" },
    {value : "TW", label :"Taiwan, Republic of China" },
    {value : "GB", label :"United Kingdom" },
    {value : "US", label :"United States of America" },
    {value : "UY", label :"Uruguay" },
    {value : "UZ", label :"Uzbekistan" },
    {value : "VU", label :"Vanuatu" },
    {value : "VE", label :"Venezuela (Bolivarian Republic of)" },
    {value : "VN", label :"Viet Nam" },
    {value : "VI", label :"Virgin Islands, US" },
    {value : "WF", label :"Wallis and Futuna Islands" },
    {value : "EH", label :"Western Sahara" },
    {value : "YE", label :"Yemen" },
    {value : "ZM", label :"Zambia" },
    { value: "ZW", label: "Zimbabwe" },
]