import Head from "next/head";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../pages/firebase/firebase";

export default function Nav() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthStateChanged(auth, user => {
      setUser(user)
    })
  }, [])

  return (
<>
      <Head> 
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <header className="bg-zinc-900">
        <a href="/" className="logo font-semibold">
          spot<span className="colorlogo">PHOTO</span>.com
        </a>
        <nav>
          <ul>
            <li>
              <Link href="/les-spots">
                <a className="hover-underline">Les spots</a>
              </Link>
            </li>
            {user ? (
              <li>
                <Link href="/account/">
                  <a className="hover-underline">Mon compte</a>
                </Link>
              </li>
            ) : (
              <li>
              <Link href="/account/">
                <a className="hover-underline">Se connecter</a>
              </Link>
            </li>
            )}
            {user !== null ? (
              <li>
                <Link href="/addspot">
                  <a className="hover-underline">Ajouter un spot</a>
                </Link>
              </li>
            ) : null}
            <li>
              <Link href="/about">
                <a className="hover-underline">Qui sommes-nous ?</a>
              </Link>
            </li>
          </ul>
        </nav>
      </header>
            </>
   
  );
}
