import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "./firebase/firebase";

export default function Nav() {
  const [user, setUser] = useState(null);

  onAuthStateChanged(auth, (currentUser) => {
    setUser(currentUser);
  });
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <header>
        <a href="/" className="logo">
          spot<span className="colorlogo">PHOTO</span>.com
        </a>
        <nav>
          <ul>
            <li>
              <Link href="/les-spots" className="hover-underline">
                Les spots
              </Link>
            </li>
            <li>
              <Link href="/account/" className="hover-underline">
                {user ? "Mon compte" : "S'inscrire"}
              </Link>
            </li>
            <li>
              <Link href="/addspot" className="hover-underline">
                {user ? "Ajouter un spot" : "Ajouter un spot"}
              </Link>
            </li>
            <li>
              <Link href="/about" className="hover-underline">
                Qui sommes-nous ?
              </Link>
            </li>
          </ul>
        </nav>
      </header>
    </Head>
  );
}
